### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by bkchr** [Lukazoid/lz_quic#1]
Hi, did you follow quicwg drafts to create this implementation? If yes, did you already use third draft?

**Comment by Lukazoid** [comment]
Hi bkchr,

This implementation is still very early days (there is still no handshake being performed). I was originally following the original google quic documents however I now have a branch ietf-draft-08 with the intention of getting this implementation to follow that version of the protocol.

I will try and get a README written with details of the current status of this project.

**Comment by bkchr** [comment]
Ohh, I did not saw that branch! Nice. 
Any rough eta/how much is missing? I'm started to write bindings for `picoquic` in rust, but if you want, I could help you?

**Comment by Lukazoid** [comment]
There is still a lot missing, for a long time I was blindly following the gquic docs without realising about the quicwg, this meant a lot of my efforts went towards implementing the crypto handshake which is no longer necessary now quic is using TLS 1.3.

Up until now this has just been a small project to learn rust and the QUIC protocol (hence the slow progress). Help would always be appreciated, however there is a lot to do and I can't see this being usable in any form for a few months yet.
